apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespaces: argocd

bases:
    - https://github.com/argoproj/argo-cd/manifests/crds?ref=v1.6.2
    - https://github.com/argoproj/argo-cd/manifests/base?ref=v1.6.2